# Generated by Django 3.2.8 on 2021-11-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TContainer',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='number')),
                ('openid', models.CharField(blank=True, max_length=255, null=True, verbose_name='openid')),
                ('container_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('container_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='price')),
                ('picture_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='stock')),
            ],
            options={
                'verbose_name': 'container',
                'verbose_name_plural': 'container',
                'db_table': 't_container',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('openid', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='openid')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='nickname')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='session_key')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 't_user',
                'managed': True,
            },
        ),
    ]
