# global configs
Global:
  checkpoints: null
  pretrained_model: null
  # pretrained_model: "./pd_model_trace/ISE/ISE_M_model" # pretrained ISE model for Market1501
  # pretrained_model: "./pd_model_trace/ISE/ISE_MS_model" # pretrained ISE model for MSMT17
  output_dir: "./output/"
  device: "gpu"
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 120
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 128, 256]
  save_inference_dir: "./inference"
  eval_mode: "retrieval"

# model architecture
Arch:
  name: "RecModel"
  infer_output_key: "features"
  infer_add_softmax: False
  Backbone: 
    name: "ResNet50_last_stage_stride1"
    pretrained: True
  BackboneStopLayer:
    name: "avg_pool"
  Neck:
    name: "BNNeck"
    num_features: 2048
  Head:
    name: "FC"  
    embedding_size: 2048
    class_num: 751
 
# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
    - SupConLoss:
        weight: 1.0
        views: 2
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.04
  regularizer:
    name: 'L2'
    coeff: 0.0005

# data loader for train and eval
DataLoader:
  Train:
    dataset:
        name: "Market1501" # ["Market1501", "MSMT17"]
        image_root: "./dataset"
        cls_label_path: "bounding_box_train"
        transform_ops:
          - ResizeImage:
              size: [128, 256]
              interpolation: 'bicubic'
              backend: 'pil'
          - RandFlipImage:
              flip_code: 1
          - Pad:
              padding: 10
              fill: 0
          - RandomCrop:
              size: [128, 256]
              pad_if_needed: False
          - NormalizeImage:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ''
          - RandomErasing:
              EPSILON: 0.5
              sl: 0.02
              sh: 0.4
              r1: 0.3
              mean: [0.485, 0.456, 0.406] 

    sampler:
        name: PKSampler
        batch_size: 16
        sample_per_id: 4
        drop_last: True
        shuffle: True
    loader:
        num_workers: 6
        use_shared_memory: True
  Eval:
    Query:
      dataset: 
        name: "Market1501" # ["Market1501", "MSMT17"]
        image_root: "./dataset"
        cls_label_path: "query"
        transform_ops:
          - ResizeImage:
              size: [128, 256]
              interpolation: 'bicubic'
              backend: 'pil'
          - NormalizeImage:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ''
      sampler:
        name: DistributedBatchSampler
        batch_size: 64
        drop_last: False
        shuffle: False
      loader:
        num_workers: 6
        use_shared_memory: True

    Gallery:
      dataset: 
        name: "Market1501" # ["Market1501", "MSMT17"]
        image_root: "./dataset"
        cls_label_path: "bounding_box_test"
        transform_ops:
          - ResizeImage:
              size: [128, 256]
              interpolation: 'bicubic'
              backend: 'pil'
          - NormalizeImage:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ''
      sampler:
        name: DistributedBatchSampler
        batch_size: 64
        drop_last: False
        shuffle: False
      loader:
        num_workers: 6
        use_shared_memory: True

Metric:
  Eval:
    - Recallk:
        topk: [1, 5]
    - mAP: {}

