Global:
  infer_imgs: "./images/PULC/vehicle_attribute/0002_c002_00030670_0.jpg"
  inference_model_dir: "./models/vehicle_attribute_infer"
  batch_size: 1
  use_gpu: True
  enable_mkldnn: True
  cpu_num_threads: 10
  benchmark: False
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

PreProcess:
  transform_ops:
    - ResizeImage:
        size: [256, 192]
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
        channel_num: 3
    - ToCHWImage:

PostProcess:
  main_indicator: VehicleAttribute
  VehicleAttribute:
    color_threshold: 0.5
    type_threshold: 0.5
  
