# global configs
Global:
  checkpoints: null
  pretrained_model: "ram_plus.pdparams"
  output_dir: ./output/
  device: cpu
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 120
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 384, 384]
  save_inference_dir: ./inference


# mixed precision
AMP:
  use_amp: False
  use_fp16_test: False
  scale_loss: 128.0
  use_dynamic_loss_scaling: True
  use_promote: False
  # O1: mixed fp16, O2: pure fp16
  level: O1


# model architecture
Arch:
  name: ram_plus
  vit: swin_l
  pretrain_clip: ./ViT-B-32.pdparams
  stage: train
 
# loss function config for traing/eval process
Loss:
  Train:
    - RAMLoss:
        weight: 1.0
        mode: "pretrain"
  Eval:
    - RAMLoss:
        weight: 1.0
        mode: "pretrain"


Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Piecewise
    decay_epochs: [30, 60, 90]
    values: [0.01, 0.001, 0.0001, 0.00001]
  regularizer:
    name: 'L2'
    coeff: 0.0001


# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: RAM_pretrain_dataset
      ann_file: [./visual-genome/vg_ram.json]

    sampler:
      name: DistributedBatchSampler
      batch_size: 1
      drop_last: False
      shuffle: True
    loader:
      num_workers: 1
      use_shared_memory: True

  Eval:
    dataset: 
      name: RAM_pretrain_dataset
      ann_file: [./visual-genome/vg_ram.json]
    sampler:
      name: DistributedBatchSampler
      batch_size: 1
      drop_last: False
      shuffle: False
    loader:
      num_workers: 1
      use_shared_memory: True

Infer:
  infer_imgs: docs/images/inference_deployment/whl_demo.jpg
  batch_size: 1
  transforms:
    - DecodeImage:
        to_rgb: True
        channel_first: False
    - ResizeImage:
        resize_short: 384
    - CropImage:
        size: 384
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:
  PostProcess:
    name: RamOutPut
    language: "cn"
    tag_list: "ppcls/utils/RAM/ram_tag_list.txt"
    tag_list_chinese: "ppcls/utils/RAM/ram_tag_list_chinese.txt"

