Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output
  device: gpu
  save_interval: -1
  eval_during_train: true
  eval_interval: 1
  epochs: 1024
  print_batch_step: 20
  use_visualdl: false
  use_dali: false
  train_mode: fixmatch_ccssl
  image_shape: [3, 32, 32]
  save_inference_dir: ./inference

SSL:
  T: 1
  threshold: 0.95

EMA:
  decay: 0.999

Arch:
  name: WideResNetCCSSL
  widen_factor: 2
  depth: 28
  drop_rate: 0
  num_classes: &sign_num_classes 10
  low_dim: 64
  proj: true
  proj_after: false

  # use_sync_bn: true

Loss:
  Train:
    - CELoss:
        weight: 1.0
        reduction: "mean"
  Eval:
    - CELoss:
        weight: 1.0
  
UnLabelLoss:
  Train:
    - CCSSLCeLoss:
        weight: 1.
    - SoftSupConLoss:
        weight: 1.0
        temperature: 0.07
    # - CCSSLLoss:
    #     CELoss:
    #       weight: 1.0
    #       reduction: "none"
    #     SoftSupConLoss:
    #       weight: 1.0
    #       temperature: 0.07
    #     weight: 1.

Optimizer:
  name: Momentum
  momentum: 0.9
  use_nesterov: true
  weight_decay: 0.001
  lr:
    name: 'cosine_schedule_with_warmup'
    learning_rate: 0.03
    num_warmup_steps: 0
    num_training_steps: 524800

DataLoader:
  mean: &sign_mean [0.4914, 0.4822, 0.4465]
  std: &sign_std [0.2471, 0.2435, 0.2616]
  Train:
    dataset:
      name: CIFAR10SSL
      data_file: null
      mode: 'train'
      download: true
      sample_per_label: 400
      expand_labels: 1
      transform_ops:
        # - RandomHorizontalFlip:
        #     prob: 0.5
        # - RandomCrop:
        #     size: 32
        #     padding: 4
        #     padding_mode: "reflect"
        - ToTensor:
        - Normalize:
            mean: *sign_mean
            std: *sign_std
    
    sampler:
      name: BatchSampler    # DistributedBatchSampler
      batch_size: 64
      drop_last: true
      shuffle: false
    loader:
      num_workers: 4
      use_shared_memory: true
  


  UnLabelTrain:
    dataset:
      name: CIFAR10SSL
      data_file: null
      mode: 'train'
      download: true

      transform_w:
        # - RandomHorizontalFlip:
        #     prob: 0.5
        # - RandomCrop:
        #     size: 32
        #     padding: 4
        #     padding_mode: 'reflect'
        - ToTensor:
        - Normalize:
            mean: *sign_mean
            std: *sign_std

      transform_s1:
        # - RandomHorizontalFlip:
        #         prob: 0.5
        # - RandomCrop:
        #     size: 32
        #     padding: 4
        #     padding_mode: 'reflect'
        # - RandAugmentMC:
        #     n: 2
        #     m: 10
        - ToTensor:
        - Normalize:
            mean: *sign_mean
            std: *sign_std
      
      transform_s2:
        # - RandomResizedCrop:
        #     size: 32
        # - RandomHorizontalFlip:
        #     prob: 0.5
        # - RandomApply:
        #     transforms:
        #       - ColorJitter:
        #           brightness: 0.4
        #           contrast: 0.4
        #           saturation: 0.4
        #           hue: 0.1
        #     p: 0.8
        # - RandomGrayscale:
        #     p: 0.2
        - ToTensor:
        # - Normalize:
        #     mean: *sign_mean
        #     std: *sign_std

    sampler:
      name: BatchSampler   # DistributedBatchSampler
      batch_size: 448
      drop_last: true
      shuffle: false
    loader:
      num_workers: 4
      use_shared_memory: true

  Eval:
    dataset:
      name: CIFAR10SSL
      mode: 'test'
      download: true
      data_file: null
      transform_ops:
        - ToTensor:
        - Normalize:
          mean: *sign_mean
          std: *sign_std
    sampler:
      name: DistributedBatchSampler
      batch_size: 64
      drop_last: False
      shuffle: True
    loader:
      num_workers: 4
      use_shared_memory: true



Metric:
  Eval:
    - TopkAcc:
        topk: [1, 5]