Global:
  infer_imgs: "./images/PULC/mlt/ILSVRC2012_val_00010000_5989.jpg"
  inference_model_dir: "./models/mlt_cls_infer"
  batch_size: 1
  use_gpu: True
  enable_mkldnn: False
  cpu_num_threads: 10
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

PreProcess:
  transform_ops:
    - ResizeImage:
        size: [80, 160]
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
        channel_num: 3
    - ToCHWImage:

PostProcess:
  main_indicator: Topk
  Topk:
    topk: 2
    class_id_map_file: "../dataset/mlt/label_list.txt"
  SavePreLabel:
    save_dir: ./pre_label/
