base_config_file: ppcls/configs/PULC/vehicle_attr/PPLCNet/PPLCNet_x1_0_search.yaml
distill_config_file: ppcls/configs/PULC/vehicle_attr/Distillation/PPLCNet_x1_0_distillation.yaml

gpus: 0,1,2,3
output_dir: output/search_vehicle_attr
search_times: 3
search_dict:
  - search_key: lrs
    replace_config:
      - Optimizer.lr.values
    search_values:
      - [0.0001, 0.00001, 0.000001, 0.0000001]
      - [0.0002, 0.00002, 0.000002, 0.0000002]
      - [0.0004, 0.00004, 0.000004, 0.0000004]
      - [0.0008, 0.00008, 0.000008, 0.0000008]
      - [0.001, 0.0001, 0.00001, 0.000001]
  - search_key: ra_probs
    replace_config:
      - DataLoader.Train.dataset.transform_ops.2.TimmAutoAugment.prob
    search_values: [0.0, 0.1, 0.3, 0.5]
  - search_key: re_probs
    replace_config:
      - DataLoader.Train.dataset.transform_ops.7.RandomErasing.EPSILON
    search_values: [0.0, 0.1, 0.3, 0.5]
  - search_key: lr_mult_list
    replace_config:
      - Arch.lr_mult_list
    search_values:
      - [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
      - [0.0, 0.4, 0.4, 0.8, 0.8, 1.0]
      - [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
# teacher:
#   rm_keys:
#     - Arch.lr_mult_list
#   search_values:
#     - ResNet101_vd
#     - ResNet50_vd
# final_replace:
#   Arch.lr_mult_list: Arch.models.1.Student.lr_mult_list

