# global configs
Global:
  pretrained_model: ./pretrained/general_PPLCNet_x2_5_pretrained_v1.0_quant
  # used for static mode and model export
  image_shape: [3, 224, 224]
  save_inference_dir: ./inference/general_PPLCNet_x2_5_quant/inference

# for quantizaiton or prune model
Slim:
  ## for prune
  quant:
    name: pact

# model architecture
Arch:
  name: RecModel

  Backbone: 
    name: PPLCNet_x2_5
    pretrained: False
    use_ssld: True
  BackboneStopLayer:
    name: "flatten"
  Neck:
    name: FC
    embedding_size: 1280
    class_num: 512
  Head:
    name: ArcMargin 
    embedding_size: 512
    class_num: 185341
    margin: 0.2
    scale: 30

# indexing engine config
IndexProcess:
  image_root: "./drink_dataset_v1.0/gallery/"
  data_file:  "./drink_dataset_v1.0/gallery/drink_label.txt"
  delimiter: "\t"
  batch_size: 2
  transform_ops:
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
        order: ''
    - ToCHWImage:
