Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output
  device: gpu
  save_interval: -1
  eval_during_train: true
  eval_interval: 1
  epochs: 1024
  iter_per_epoch: 1024
  print_batch_step: 20
  use_visualdl: false
  use_dali: false
  train_mode: fixmatch_ccssl
  image_shape: [3, 32, 32]
  save_inference_dir: ./inference

SSL:
  T: 1
  threshold: 0.95

EMA:
  decay: 0.999

Arch:
  name: RecModel
  infer_output_key: logits
  infer_add_softmax: false
  Backbone:
    name: WideResNet
    widen_factor: 8
    depth: 28
    dropout: 0 
    num_classes: 100
    low_dim: 64
    proj: true
    proj_after: false

  Decoup:
    name: Decoup
    logits_index: 0
    features_index: 1 

  use_sync_bn: true

Loss:
  Train:
    - CELoss:
        weight: 1.0
        reduction: "mean"
  Eval:
    - CELoss:
        weight: 1.0
  
UnLabelLoss:
  Train:
    - CCSSLCeLoss:
        weight: 1.
    - SoftSupConLoss:
        weight: 1.0
        temperature: 0.07

Optimizer:
  name: Momentum
  momentum: 0.9
  use_nesterov: true
  weight_decay: 0.001
  lr:
    name: 'cosine_schedule_with_warmup'
    learning_rate: 0.03
    num_warmup_steps: 0
    num_training_steps: 524800

DataLoader:
  mean: [0.5071, 0.4867, 0.4408]
  std: [0.2675, 0.2565, 0.2761]
  Train:
    dataset:
      name: CIFAR100SSL
      data_file: null
      mode: 'train'
      download: true
      sample_per_label: 100
      expand_labels: 1
      transform_ops:
        - RandomHorizontalFlip:
            prob: 0.5
        - RandomCrop:
            size: 32
            padding: 4
            padding_mode: "reflect"
        - ToTensor:
        - Normalize:
            mean: [0.5071, 0.4867, 0.4408]
            std: [0.2675, 0.2565, 0.2761]
    
    sampler:
      name: DistributedBatchSampler
      batch_size: 16
      drop_last: true
      shuffle: true
    loader:
      num_workers: 4
      use_shared_memory: true
  
  UnLabelTrain:
    dataset:
      name: CIFAR100SSL
      data_file: null
      mode: 'train'
      download: true

      transform_w:
        - RandomHorizontalFlip:
            prob: 0.5
        - RandomCrop:
            size: 32
            padding: 4
            padding_mode: 'reflect'
        - ToTensor:
        - Normalize:
            mean: [0.5071, 0.4867, 0.4408]
            std: [0.2675, 0.2565, 0.2761]

      transform_s1:
        - RandomHorizontalFlip:
                prob: 0.5
        - RandomCrop:
            size: 32
            padding: 4
            padding_mode: 'reflect'
        - RandAugmentMC:
            n: 2
            m: 10
        - ToTensor:
        - Normalize:
            mean: [0.5071, 0.4867, 0.4408]
            std: [0.2675, 0.2565, 0.2761]
      
      transform_s2:
        - RandomResizedCrop:
            size: 32
        - RandomHorizontalFlip:
            prob: 0.5
        - RandomApply:
            transforms:
              - ColorJitter:
                  brightness: 0.4
                  contrast: 0.4
                  saturation: 0.4
                  hue: 0.1
            p: 0.8
        - RandomGrayscale:
            p: 0.2
        - ToTensor:

    sampler:
      name: DistributedBatchSampler
      batch_size: 112
      drop_last: true
      shuffle: true
    loader:
      num_workers: 4
      use_shared_memory: true

  Eval:
    dataset:
      name: CIFAR100SSL
      mode: 'test'
      download: true
      data_file: null
      transform_ops:
        - ToTensor:
        - Normalize:
            mean: [0.5071, 0.4867, 0.4408]
            std: [0.2675, 0.2565, 0.2761]
    sampler:
      name: DistributedBatchSampler
      batch_size: 16
      drop_last: False
      shuffle: True
    loader:
      num_workers: 4
      use_shared_memory: true

Metric:
  Eval:
    - TopkAcc:
        topk: [1, 5]