# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: "./output/"
  device: "gpu"
  save_interval: 1
  eval_mode: "retrieval"
  eval_during_train: True
  eval_interval: 1
  epochs: 120
  print_batch_step: 10
  use_visualdl: False
  image_shape: [3, 224, 224]
  infer_imgs:
  save_inference_dir: "./inference"
  feature_normalize: True

Arch:  
  name: "RecModel"
  Backbone:
    name: "ResNet50"
    pretrained: True
  BackboneStopLayer: 
    name: "flatten"
    output_dim: 2048
  Head:
    name: "FC"
    class_num: 5013
    embedding_size: 2048
    # margin: 0.5
    # scale:  80
  infer_output_key:  "features"
  infer_add_softmax: "false"

Loss:
  Train:
    - CELoss:
        weight: 1.0
    # - TripletLoss:  
    #     margin: 0.1
    #     weight: 0.1
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Piecewise
    learning_rate: 0.1
    decay_epochs: [30, 60, 90]
    values: [0.1, 0.01, 0.001, 0.0001]
  regularizer:
    name: 'L2'
    coeff: 0.0001

DataLoader:
  Train:
    dataset:
      name: ICartoonDataset
      image_root:  "./dataset/iCartoonFace"
      cls_label_path:  "./dataset/iCartoonFace/train_list.txt"
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 0.00392157
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
        name: DistributedBatchSampler
        #num_instances: 2
        batch_size: 256
        drop_last: False
        shuffle: True
    loader:
        num_workers: 6
        use_shared_memory: True
  
  Eval:
    Query:
      dataset: 
        name: ICartoonDataset
        image_root: "./dataset/iCartoonFace"
        cls_label_path: "./dataset/iCartoonFace/query.txt"
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              resize_short: 256
          - CropImage:
              size: 224
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ''
      sampler:
          name: DistributedBatchSampler
          batch_size: 64
          drop_last: False
          shuffle: False
      loader:
          num_workers: 8
          use_shared_memory: True

    Gallery:
      dataset: 
          name: ICartoonDataset
          image_root: "./dataset/iCartoonFace"
          cls_label_path: "./dataset/iCartoonFace/gallery.txt"
          transform_ops:
            - DecodeImage:
                to_rgb: True
                channel_first: False
            - ResizeImage:
                resize_short: 256
            - CropImage:
                size: 224
            - NormalizeImage:
                scale: 0.00392157
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
                order: ''
      sampler:
          name: DistributedBatchSampler
          batch_size: 64
          drop_last: False
          shuffle: False
      loader:
          num_workers: 8
          use_shared_memory: True

Metric:
    Train:
    - TopkAcc:
        topk: [1, 5]
    Eval:
    - Recallk:
        topk: [1]
