Global:
  infer_imgs: "./drink_dataset_v1.0/test_images/001.jpeg"
  det_inference_model_dir: "./models/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer"
  rec_inference_model_dir: "./models/general_PPLCNet_x2_5_lite_binary_v1.0_infer"
  rec_nms_thresold: 0.05
  
  batch_size: 1
  image_shape: [3, 640, 640]
  threshold: 0.2
  max_det_results: 5
  label_list:
  - foreground

  use_gpu: True
  enable_mkldnn: True
  cpu_num_threads: 10
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

DetPreProcess:
  transform_ops:
    - DetResize:
        interp: 2
        keep_ratio: false
        target_size: [640, 640]
    - DetNormalizeImage:
        is_scale: true
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - DetPermute: {}
DetPostProcess: {}

RecPreProcess:
  transform_ops:
    - ResizeImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:

RecPostProcess:
  main_indicator: Binarize
  Binarize:
    method: "sign"

# indexing engine config
IndexProcess:
  index_method: "Flat"  # supported: HNSW32, Flat
  image_root: "./drink_dataset_v1.0/gallery/"
  index_dir: "./drink_dataset_v1.0/index_bin"
  data_file:  "./drink_dataset_v1.0/gallery/drink_label.txt"
  index_operation: "new"  # suported: "append", "remove", "new"
  delimiter: "\t"
  dist_type: "hamming"
  embedding_size: 512
  batch_size: 32
  return_k: 5
  hamming_radius: 100
