# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 100
  print_batch_step: 50
  use_visualdl: False
  train_mode: fct_trans
  eval_mode: retrieval
  # used for static mode and model export
  image_shape: [3, 224, 224]
  save_inference_dir: ./inference
  # training model under @to_static
  to_static: False
  update_freq: 2  # for 8 cards

# model architecture
Arch:
  name: FCT
  old_model_name: ResNet50
  old_model_path: ./pretrained/imagenet_old
  new_model_name: ResNet50
  new_model_path: ./pretrained/imagenet_new
  side_model_path: ./pretrained/imagenet_500_simclr
  trans_config:
    old_embedding_dim: 128
    new_embedding_dim: 128
    side_info_dim: 128
    inner_dim: 2048


# loss function config for traing/eval process
Loss:
  Train:
    - MSMLoss:
        weight: 1.0
  Eval:
    - MSMLoss:
        weight: 1.0

Optimizer:
  name: Adam
  weight_decay: 0.000030517578125
  use_nesterov: False
  no_weight_decay_name: ._mean ._variance
  lr:
    # for 8 cards
    name: Cosine
    learning_rate: 0.0005  # for total_batch_size 1024
    eta_min: 0
    warmup_epoch: 5
    warmup_start_lr: 0.0001  # learning_rate * 1 / warmup_epoch
    by_epoch: True

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: ./dataset/ILSVRC2012/
      cls_label_path: ./dataset/ILSVRC2012/train_list.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
            backend: pil
        - RandCropImage:
            size: 224
            interpolation: bicubic
            backend: pil
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 128
      drop_last: False
      shuffle: True
    loader:
      num_workers: 4
      use_shared_memory: True

  Eval:
    dataset: 
      name: ImageNetDataset
      image_root: ./dataset/ILSVRC2012/
      cls_label_path: ./dataset/ILSVRC2012/val_list.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
            backend: pil
        - ResizeImage:
            resize_short: 256
            interpolation: bicubic
            backend: pil
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 128
      drop_last: False
      shuffle: False
    loader:
      num_workers: 4
      use_shared_memory: True

Infer:
  infer_imgs: docs/images/inference_deployment/whl_demo.jpg
  batch_size: 10
  transforms:
    - DecodeImage:
        to_rgb: True
        channel_first: False
        backend: pil
    - ResizeImage:
        resize_short: 256
        interpolation: bicubic
        backend: pil
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:
  PostProcess:
    name: Topk
    topk: 5
    class_id_map_file: ppcls/utils/imagenet1k_label_list.txt


Metric:
  Eval:
    - mAP: null
    - Recallk: null
