from .resnet_variant import ResNet50_last_stage_stride1
from .vgg_variant import VGG19Sigmoid
from .pp_lcnet_variant import PPLCNet_x2_5_Tanh
from .swin_transformer_variant import SwinTransformer_base_patch4_window7_224_SOLIDER
from .swin_transformer_variant import SwinTransformer_small_patch4_window7_224_SOLIDER
from .swin_transformer_variant import SwinTransformer_tiny_patch4_window7_224_SOLIDER
