Global:
  infer_imgs: "./images/PULC/car_exists/objects365_00001507.jpeg"
  inference_model_dir: "./models/car_exists_infer"
  batch_size: 1
  use_gpu: True
  enable_mkldnn: False
  cpu_num_threads: 10
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

PreProcess:
  transform_ops:
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
        channel_num: 3
    - ToCHWImage:

PostProcess:
  main_indicator: ThreshOutput
  ThreshOutput:
    threshold: 0.5
    label_0: no_car
    label_1: contains_car
  SavePreLabel:
    save_dir: ./pre_label/
