# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 450
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 188, 188]
  save_inference_dir: ./inference

# model ema
EMA:
  decay: 0.9999


# mixed precision
AMP:
  use_amp: False
  use_fp16_test: False
  scale_loss: 128.0
  use_dynamic_loss_scaling: True
  use_promote: False
  # O1: mixed fp16, O2: pure fp16
  level: O1


# model architecture
Arch:
  name: TinyNet_B
  class_num: 1000
  override_params:
    batch_norm_momentum: 0.9
    batch_norm_epsilon: 1e-5
    depth_trunc: round
    drop_connect_rate: 0.1

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
        epsilon: 0.1
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: RMSProp
  momentum: 0.9
  rho: 0.9
  epsilon: 0.001
  one_dim_param_no_weight_decay: True
  lr:
    name: Step
    learning_rate: 0.048
    step_size: 2.4
    gamma: 0.97
    warmup_epoch: 3
    warmup_start_lr: 1e-6
  regularizer:
    name: 'L2'
    coeff: 1e-5

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: ./dataset/ILSVRC2012/
      cls_label_path: ./dataset/ILSVRC2012/train_list.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
            backend: pil
        - RandCropImage:
            size: 188
            interpolation: bicubic
            backend: pil
            use_log_aspect: True
        - RandFlipImage:
            flip_code: 1
        - ColorJitter:
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 128
      drop_last: False
      shuffle: True
    loader:
      num_workers: 4
      use_shared_memory: True

  Eval:
    dataset:
      name: ImageNetDataset
      image_root: ./dataset/ILSVRC2012/
      cls_label_path: ./dataset/ILSVRC2012/val_list.txt
      transform_ops:
        - DecodeImage:
            to_np: False
            channel_first: False
            backend: pil
        - ResizeImage:
            resize_short: 214
            interpolation: bicubic
            backend: pil
        - CropImage:
            size: 188
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 128
      drop_last: False
      shuffle: False
    loader:
      num_workers: 4
      use_shared_memory: True

Infer:
  infer_imgs: docs/images/inference_deployment/whl_demo.jpg
  batch_size: 10
  transforms:
    - DecodeImage:
        to_np: False
        channel_first: False
    - ResizeImage:
        resize_short: 214
        interpolation: bicubic
        backend: pil
    - CropImage:
        size: 188
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:
  PostProcess:
    name: Topk
    topk: 5
    class_id_map_file: ppcls/utils/imagenet1k_label_list.txt

Metric:
  Train:
    - TopkAcc:
        topk: [1, 5]
  Eval:
    - TopkAcc:
        topk: [1, 5]
