# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/WaitDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaitDialog(object):
    def setupUi(self, WaitDialog):
        WaitDialog.setObjectName("WaitDialog")
        WaitDialog.setWindowModality(QtCore.Qt.NonModal)
        WaitDialog.resize(324, 78)
        self.verticalLayout = QtWidgets.QVBoxLayout(WaitDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msgLabel = QtWidgets.QLabel(WaitDialog)
        self.msgLabel.setObjectName("msgLabel")
        self.verticalLayout.addWidget(self.msgLabel)
        self.progressBar = QtWidgets.QProgressBar(WaitDialog)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        spacerItem = QtWidgets.QSpacerItem(20, 1,
                                           QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(WaitDialog)
        QtCore.QMetaObject.connectSlotsByName(WaitDialog)

    def retranslateUi(self, WaitDialog):
        _translate = QtCore.QCoreApplication.translate
        WaitDialog.setWindowTitle(_translate("WaitDialog", "请等待"))
        self.msgLabel.setText(_translate("WaitDialog", "正在更新索引库，请等待。。。"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaitDialog = QtWidgets.QDialog()
    ui = Ui_WaitDialog()
    ui.setupUi(WaitDialog)
    WaitDialog.show()
    sys.exit(app.exec_())
