# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: "./output/"
  device: "gpu"
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 20
  print_batch_step: 20
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 224, 224]
  save_inference_dir: "./inference"
  use_multilabel: True

# model architecture
Arch:
  name: "DistillationModel"
  class_num: &class_num 6
  # if not null, its lengths should be same as models
  pretrained_list:
  # if not null, its lengths should be same as models
  infer_model_name: "Student"
  freeze_params_list:
  - True
  - False
  use_ssld: True
  models:
    - Teacher:
        name: ResNet50_vd
        class_num: *class_num
    - Student:
        name: PPLCNet_x1_0
        class_num: *class_num
        pretrained: True
        use_ssld: True

# loss function config for traing/eval process
Loss:
  Train:
    - DistillationMultiLabelLoss:
        weight: 1.0
        model_names: ["Student"]
        weight_ratio: True
        size_sum: True
    - DistillationDMLLoss:
        weight: 1.0
        weight_ratio: True
        sum_across_class_dim: False
        model_name_pairs:
        - ["Student", "Teacher"]
    
  Eval:
    - MultiLabelLoss:
        weight: 1.0
        weight_ratio: True
        size_sum: True

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.02
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    coeff: 0.0005

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: MultiLabelDataset
      image_root: "dataset/table_attribute/"
      cls_label_path: "dataset/table_attribute/train_list.txt"
      label_ratio: True
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            size: [224, 224]
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 64
      drop_last: True
      shuffle: True
    loader:
      num_workers: 4
      use_shared_memory: True
  Eval:
    dataset:
      name: MultiLabelDataset
      image_root: "dataset/table_attribute/"
      cls_label_path: "dataset/table_attribute/val_list.txt"
      label_ratio: True
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            size: [224, 224]
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 64
      drop_last: False
      shuffle: False
    loader:
      num_workers: 4
      use_shared_memory: True

Infer:
  infer_imgs: deploy/images/PULC/table_attribute/val_3253.jpg
  batch_size: 10
  transforms:
    - DecodeImage:
        to_rgb: True
        channel_first: False
    - ResizeImage:
        size: [224, 224]
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:
  PostProcess:
    name: TableAttribute
    source_threshold: 0.5
    number_threshold: 0.5
    color_threshold: 0.5
    clarity_threshold : 0.5
    obstruction_threshold: 0.5
    angle_threshold: 0.5

Metric:
  Eval:
    - ATTRMetric:


